
# Site definitions
title = "dongheenam"
baseURL = "https://www.dongheenam.info/"
languageCode = "en-au"
theme = "dnaminfo-theme"

# set timeout to 2 minutes
timeout = 120000

# ignore TeX files
ignoreFiles = [ "\\.tex$" ]

# site infos
[params]
  author = "Donghee Nam"
  description = "Giving insight on the world's most commonly used language"

# flatten posts directory structure
[permalinks]
  posts = "/posts/:title/"

# Goldmark Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

# Algolia indexing
[outputs]
home = ["HTML","Algolia"]

[outputFormats.Algolia]
  mediaType = "application/json"
  baseName = "algolia"
  isPlainText = true
  notAlternative = true