# Site definitions
title: dongheenam
baseURL: https://www.dongheenam.info/
languageCode: en-auSvelte store example 1
theme: dnaminfo-theme

# site parameters
params:
  author: Donghee Nam
  description: Giving insight on the world's most commonly used language

# Goldmark settings
markup:
  goldmark:
    parser:
      attribute:
        block: false
        title: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    noClasses: false
    style: github-dark
  
# build settings
timeout: 600000

ignoreFiles:
  - \.tex$

permalinks:
  posts: /posts/:title/

outputs:
  home:
    - HTML
    - Algolia

outputFormats:
  Algolia:
    mediaType: application/json
    baseName: algolia
    isPlainText: true
    notAlternative: true