[[main]]
    name = "Posts"
    url = "/posts/"
    weight = "10"

[[main]]
    name = "Courses"
    url = "/courses/"
    weight = "20"

[[main]]
    name = "Tags"
    url = "/tags/"
    weight = "30"
    
[[main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = "40"