main:
  - name: Home
    url: /
    weight: 10
  - name: Posts
    url: /posts/
    weight: 20
  - name: Courses
    url: /courses/
    weight: 30
  - name: Tags
    url: /tags/
    weight: 40
  - name: Portfolio
    url: /portfolio/
    weight: 50