[build]
    publish = "public"
    command = "hugo --gc --minify --baseURL=https://dongheenam.netlify.app/"

[context.production.environment]
    HUGO_VERSION = "0.78.2"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
