[build]
    publish = "public"
    command = "hugo --gc --minify --templateMetrics"

[context.production.environment]
    HUGO_VERSION = "0.84.3"
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

[[headers]]
    for = "/portfolio/*"
    [headers.values]
        X-Robots-Tag = "noindex"