[build]
    publish = "public"
    command = "hugo --gc --minify --templateMetrics"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

[context.production.environment]
    HUGO_VERSION = "0.81.0"
    HUGO_ENABLEGITINFO = "true"
