[build]
    # command = "npm run build"
    command = "bash ./build.sh"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.118.2"
    DART_SASS_VERSION = "1.67.0"
    HUGO_ENABLEGITINFO = "true"

# [[plugins]]
#     package = "netlify-plugin-hugo-cache-resources"
#     [plugins.inputs]
#         debug = false

# [[headers]]
#     for = "/portfolio/*"
#     [headers.values]
#         X-Robots-Tag = "noindex"