[build]
    publish = "public"
    command = "npm run build"

[context.production.environment]
    NODE_VERSION = "latest"
    HUGO_VERSION = "latest"
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"
    [plugins.inputs]
        debug = false

[[headers]]
    for = "/portfolio/*"
    [headers.values]
        X-Robots-Tag = "noindex"